name: Push Glitch

on: 
 pull_request:
  types: [closed] 
jobs:
  repo-sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v3
      env:
        source_repo: "https://github.com/gamerboytr/turkishmethods-bot.git"
        source_branch: "master"
        destination_repo: ${{ secrets.glitch_git_URL }}
        destination_branch: "master"
      with:
        args: $source_repo $source_branch $destination_repo $destination_branch
